### ISSUE TITLE
Author list in files

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/pr-ompl#1]
It says the author is Ioan Sucan from Willow Garage. Shouldn't Chris be added to this?

**Comment by mkoval** [comment]
I imported this directly from @cdellin's SVN repository, so I'll let him handle this. :smile:

**Comment by siddhss5** [comment]
Haha, sure. @cdellin some clean up, a README and some comments would be great.

**Comment by mkoval** [comment]
@cdellin We're also waiting for that `or_cdchomp` documentation. :wink:
